// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: sumerapi/sumer.proto

package grpc_sumer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SumerClient is the client API for Sumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SumerClient interface {
	// Sends a greeting
	Sum(ctx context.Context, in *SumerRequest, opts ...grpc.CallOption) (*SumerResponse, error)
}

type sumerClient struct {
	cc grpc.ClientConnInterface
}

func NewSumerClient(cc grpc.ClientConnInterface) SumerClient {
	return &sumerClient{cc}
}

func (c *sumerClient) Sum(ctx context.Context, in *SumerRequest, opts ...grpc.CallOption) (*SumerResponse, error) {
	out := new(SumerResponse)
	err := c.cc.Invoke(ctx, "/sumerapi.Sumer/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumerServer is the server API for Sumer service.
// All implementations must embed UnimplementedSumerServer
// for forward compatibility
type SumerServer interface {
	// Sends a greeting
	Sum(context.Context, *SumerRequest) (*SumerResponse, error)
	mustEmbedUnimplementedSumerServer()
}

// UnimplementedSumerServer must be embedded to have forward compatible implementations.
type UnimplementedSumerServer struct {
}

func (UnimplementedSumerServer) Sum(context.Context, *SumerRequest) (*SumerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedSumerServer) mustEmbedUnimplementedSumerServer() {}

// UnsafeSumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SumerServer will
// result in compilation errors.
type UnsafeSumerServer interface {
	mustEmbedUnimplementedSumerServer()
}

func RegisterSumerServer(s grpc.ServiceRegistrar, srv SumerServer) {
	s.RegisterService(&Sumer_ServiceDesc, srv)
}

func _Sumer_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumerServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sumerapi.Sumer/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumerServer).Sum(ctx, req.(*SumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sumer_ServiceDesc is the grpc.ServiceDesc for Sumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sumerapi.Sumer",
	HandlerType: (*SumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _Sumer_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sumerapi/sumer.proto",
}
